sudo: required
dist: trusty

language: java
jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2/repository

before_install:
  # allocate commits to CI, not the owner of the deploy key
  - git config user.name "opentracingci"
  - git config user.email "opentracingci+opentracing@googlegroups.com"
  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

install:
  # Override default travis to use the maven wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - ./travis/publish.sh

branches:
  except:
    - /^[0-9]/

env:
  global:
  # Ex. travis encrypt -r org/repo BINTRAY_USER=your_github_account
  - secure: "ZKMlnphO20zMmMwsf/dU/QARdfOkzOt+iloXZtVrSeOkp3HITorfU+hr4jP2Lj96qMsRIDbvvQIUHdTWmNdCNDNUrrpjrhulQK+oEi2dBr/QvdBpkXGyANKn1hYmqrc1cWxbOMnO804Vfqcc7mkJ1EjEVPc1f46WY1QLIlvMGpdOL7SiuFRstUegDvEnCuZmRhUHg5BD2HPLvfB6bwexYrB4G6mGcxYjVrEfHHIBg/rBDmRuN59KM/T0PMYAJt+j87Ua2Cj6Tb4eg9Lq7UPWvYRk+SsQzsKWYqNyZVh86p2hNwcoblttPEFsk/y3W75+eZbHX8v02Zi0nRiS9jiQ27CBfwggxrg3EybabDR2OtmjW8BctkycNZDf2I1cXDJE3BXtNxwzsGJcMGo7IbHSLXtB4haRP0sCeuzD4R+LxeH6p++hGrbgckPSTKjn8cmAlzxPy4lzQf9NiHXtkNfTbFuvB6qL3c7WUi19QoREo3fxu9k/kTlMDNEQaWDWzuIwwqd9+/EFKbxUUKDUzyNhPDBiLlYNqAkCZ+0Cx2imnRFqzCl99+gM4kCtCQj4eGfJdovS7cWCFQCgSPLqtrXOeOohtXLk24IQmblUjuujIroNdyyzng3ShtgmNy2/u6B+4uZJZQEggaKSBuMkyk0u5NabK36Ah2E3nJpHI+2x2yg="
  # Ex. travis encrypt -r org/repo BINTRAY_KEY=xxx-https://bintray.com/profile/edit-xxx --add
  - secure: "sawPtCI+c05LJQxDRLHHR9j8nKYGzphoFP7jKeGi3dTSDIHaKXMwtUPtbYNKED207fwjXrrX8fvLPfdIIYZ1jFh+ghPViGgSVlEW0plwOQDFqpCgTF7rsGKBA6tdbVux7NbJmHxSwstHVk3gF091DHjCjE/476QDuBPdJvWwz4PzH1IZ93Xi/WdUYz388eATXzRB+q8fXZYK+t73pxyCYdwYXc3/PsFzt2srCB4xgES8tetZePntQJFjjHAgAQtBAladvgftsxpzlfafhxXxwyOb3SthQ5se2Ebj/q3M8leZKQi+cQeqnuBGeUe+rqWgav9o8cIAH2ksOcOao8xlgaliKOFQrBGoVWhwpSTnvE6bryAp23kaVrv7DT9f16lox6h28X7yhoasUg910StACSfkOgJlGaxc/o+YRMaUMb/7R+MfmRfLK75EMS/y0JurfMngHTj2ASLqGrITMxIeBNhwXaVeqCwwfylQH4SaiYOa37+8+Lvu3V2EHlJNZN6PwuODrNls7I9m1pYKpESng9LLZa9TQieSC4MHdvw/IhrpI1GHkqkVt0rvtxs2IlgtgwIA5oR0QpVHMB2vbKp1Q8ZfPukU5p028+gC3bC+51Y6qlv7xZD/JHUyGYHObvLZ9IOGfULIf8eYrCixvL5bP2Nu58BB/pSkHOHc7yqlCto="
  # Ex. travis encrypt -r org/repo GH_TOKEN=XXX-https://github.com/settings/tokens-XXX --add
  - secure: "av2rXWwyBo5eWNjLUhHGsTpQK6/VZWvgs/oILeLcX5vcDKXLTZpPaeDUS3LS1voCMeNJIMoWoM+TVypzcjSJh+dwmgMLmeCGgZkEZ4wjQYzwgifeWOXcdEtl5CNDF6aO9ghR2ZynQK49Fqf3JO/01CdLVpFQj5C5WeFBl/7XFk8UV8PyxaIFmDMSFIYVwF4UrGDi72BfVXoIYREOsN2EMRHzIApKLD0CY19Q+zGL/xAi2HJ+fbR7IJgJF2h7DdNGxblbhQvAeEUJR02mcYfEf2X/IpbB5+wV/5IIZMrzVAoOjb6HDD4hzwJw+/1BYVDXDkOvWeZDNsP2Bmkx0ajJN115T0Z0VtjVlVgnCI+D5k2mcuLO63mnX7ofpa7Xkv674lwqPbQ7U/XKODAxQZgt5b2U5Zp1o+IJFYqkBF5r2XdYiMRnRaNlZK0liytOFGf1h4s0AblZsSw6lmEayhCyItgzZlE2wacmRBqEiBkpMPUEbWRQUCrSHP7PrTPPPZPriMm7/wDOrjQr4vzArXHzDrdRNHFjVQbHZCTGAihpFzIlJzutOd/bze5FAS+z2Jdj8Ka8DpyTPUvtkmQAIHH/G518qhWfcKGz+iPoYIrKLX3ercaocaLFLbggswL8NyA16PIw7pjiv44PYy5IMy0JoNnq9FeUmp+LUO7s4BIYJ34="
  # Ex. travis encrypt -r org/repo SONATYPE_USER=your_sonatype_account
  - secure: "L6s+uXpkYmBnFCigAAm3qguxFddRo+9WzaX4zploZv5P3/JsedMrifWYVu5MeYgEX3COmyr6QmONXCPxQbaQLu2gKbOKxx29WnZm8aF0NPgvoDvHXm2vN4/53wW8Er5rC+O260uRSwlS1kLz1Z2fQcXKitJJSTzR06kICRMWxz4DSqoraBEb9WVabNvNQZGw/OLdZl5Mnj23KFQPWxdSOfTrERy5pSO4LwjrPkoj/H3paVDI/PTNNxjCeRTPLj7Sjq4CCnCqj3Xc9McazORM98eSVFbN9SVx6Yagg1mp6vXOqW+GTBJpSRsi0rhViHoDFlxQ815jKWvKAfAgPHkt9b6opEIo8OgzHEWJ6seYaSEzqmaKlNnlWSh9Y5P/oq+w5y8gKRFpwg4Uev6Bmdrpz6/lWR1XrtGdKDspvUJSKfDAJ7EmQV+tk+kT0HKAkUqa8ngvWqnxF04mkv38+iDv4ijUhKJC8pxQoVeEOFIPE+A9oH0dcVa/HOWnr7jnERon5QSNBUPovSulCceKZi+t0+yvI9MPtWfww8uQshabbtFlns1/kYsZsgIbXwfvB21Vp3FMg8rFvTyKiVDOwzmzgwPqUTLt9BSmWWSucbv4KAedchx8MIrBqeDwDrCHnzPOw6thL3F89AVVa1wMvbLnli8hl2cVLGghWCXQd4TsM0w="
  # Ex. travis encrypt -r org/repo SONATYPE_PASSWORD=your_sonatype_password
  - secure: "pMeh8kFtPQNiUGza3EF77+LLxKl0KYQ+7gFrEFdG2JaEEj+vaJlYRXS8hJ7wD/Ap+tl0gjMMHXtxUYAUehwnpLfsxEto46Z6oy8a+V6AyUUJSIzlG7CugkTBWHihcNXPztrK5PK1j+553CLYAHnIJQEY4+cDwi77Ce9a6M5+ANPmJpPUQ3VdOJV/fliaBE/nCjikqgPKrUawZMtZRMzBji6I7RbuNqmlFJD5G5q751gO8Y4gLLc1lwo7pf4o1VUQrMaj9jF4JpU03TbrFKgWUsyp9kfDL9PpgBBNGjeJl5q105jYisLkXTxLn9J73KW/N16zWbx5YkpycXnrrmsP6sRAKfz5ksxbq/PxHLhjYBFsjn535gkdxsoiCqbs6Gg2XczmiwWTleNrSftnApwa+ge8aMEOcjIVe8ni/v48u+QiEsJxNL02m7PquBS/dJIqYW5qJGwYWKcrnc25KJ4JOnfvdSGVKvv27+/gZnex/tZRs4LPJtKa6bOGRV59cJszUy7y0rzfqHVVbSWEaSFIUxB+9AxWjFnmvC9UrGG/+kmg3XsI0w8Ev2jEqO/77QYuXnDsAptDrvrwmhCHLEOTFuAxk+feKIzIW6uSyXY3zl600VJGx9BRjgzcz8LRORN6PtwkDLFL69YCvNzsLEyBZGdaMB0OsVX7Ldv+In2vHvU="
